[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS, DELETE, PUT"
    Access-Control-Allow-Origin = "*"
